<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>选择当天</description>
   <name>xzdatequeren</name>
   <tag></tag>
   <elementGuidId>9146c641-cdad-4f2d-8531-66949341f80b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = '多次报价' or . = '多次报价')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>多次报价</value>
   </webElementProperties>
</WebElementEntity>
