<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>提交审核</description>
   <name>tjsh</name>
   <tag></tag>
   <elementGuidId>963d821b-ae58-4b42-bdb8-fe53db13a253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = '提交审核' or . = '提交审核')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>提交审核</value>
   </webElementProperties>
</WebElementEntity>
