<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>工单</description>
   <name>gongdan</name>
   <tag></tag>
   <elementGuidId>2c84ee25-3586-47f0-8bdd-f1aae6490afe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sc-header&quot;]/div[3]/span[4]/div[1]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>工单</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sc-header&quot;]/div[3]/span[4]/div[1]/button/span</value>
   </webElementProperties>
</WebElementEntity>
