<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>工单</description>
   <name>gongdan-DB</name>
   <tag></tag>
   <elementGuidId>0914b64e-1ff5-429a-ac94-b1aaa9a06994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sc-header&quot;]/div[3]/span[4]/div[2]/p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>我的待办</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sc-header&quot;]/div[3]/span[4]/div[2]/p[1]</value>
   </webElementProperties>
</WebElementEntity>
